version: '3'
services:
  banking-operator-app:
    container_name: banking-rbc-operator-container
    build: .
    ports:
      - '3003:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start
    restart: always